urls = [
	'https://www.youtube.com/watch?v=qX9nf86KJ8k',
	'https://www.youtube.com/watch?v=VfLpdsELJfU',
	'https://www.youtube.com/watch?v=0DHpbYBrKPs',
	'https://www.youtube.com/watch?v=K0PuS391dsI',
	'https://www.youtube.com/watch?v=_6qZlmLrMzM',
	'https://www.youtube.com/watch?v=UA3FteJn9oc',
	'https://www.youtube.com/watch?v=66YZEptO2Zo',
	'https://www.youtube.com/watch?v=iSYIjjW--pE',
	'https://www.youtube.com/watch?v=5ZFfT347-j0',
	'https://www.youtube.com/watch?v=vGOvU7de3DM',
	'https://www.youtube.com/watch?v=AFXGZBdzf-s',
	'https://www.youtube.com/watch?v=Fa9TCNpBPBg',
	'https://www.youtube.com/watch?v=F5t4jpezDPI',
	'https://www.youtube.com/watch?v=LmrzXWsV910',
	'https://www.youtube.com/watch?v=plesqDCozKg',
	'https://www.youtube.com/watch?v=BplCjZ0HZLg',
	'https://www.youtube.com/watch?v=YEneLXIAPAs',
	'https://www.youtube.com/watch?v=qLWeE5wiiwY',
	'https://www.youtube.com/watch?v=KD5wYlYHj_U',
	'https://www.youtube.com/watch?v=jCasz8Nitlw',
	'https://www.youtube.com/watch?v=_ke6TdV2Qj0',
	'https://www.youtube.com/watch?v=5sG5lfIjVoc',
	'https://www.youtube.com/watch?v=mleWEDCNh8s',
	'https://www.youtube.com/watch?v=AhipgYwSzcU',
	'https://www.youtube.com/watch?v=joChTd_bwKk',
	'https://www.youtube.com/watch?v=Uvx7NcZ-SWY',
	'https://www.youtube.com/watch?v=uH-SZgFtP3k',
	'https://www.youtube.com/watch?v=DI-GL2v0d1Y',
	'https://www.youtube.com/watch?v=QyeTkWTRrII',
	'https://www.youtube.com/watch?v=iBgdNphFYO8',
	'https://www.youtube.com/watch?v=2fcsPzC_ZuI',
	'https://www.youtube.com/watch?v=URDW6aaO3Ro',
	'https://www.youtube.com/watch?v=EnmwIi18p5Y',
	'https://www.youtube.com/watch?v=pAwVXWqiyA0',
	'https://www.youtube.com/watch?v=u2tEDpjOxdg',
	'https://www.youtube.com/watch?v=ioiS0I2WqRQ',
	'https://www.youtube.com/watch?v=hwlroASv9ws',
	'https://www.youtube.com/watch?v=ezXOQ2cNI74',
	'https://www.youtube.com/watch?v=QLnbJ9Wn68o',
	'https://www.youtube.com/watch?v=953YmmFivvc',
	'https://www.youtube.com/watch?v=auER8X-0OgU',
	'https://www.youtube.com/watch?v=NsmoKA4Fd8w',
	'https://www.youtube.com/watch?v=ieO_uImbSA4',
	'https://www.youtube.com/watch?v=nRIzyJWTv5U',
	'https://www.youtube.com/watch?v=T8IIqc4QG7g',
	'https://www.youtube.com/watch?v=rUz0iSKTLf4',
	'https://www.youtube.com/watch?v=pDp5EBpJrQY',
	'https://www.youtube.com/watch?v=xmDpgnBZJW4',
	'https://www.youtube.com/watch?v=Q1lILNGAKwU',
	'https://www.youtube.com/watch?v=qBjlp4RLeUA',
	'https://www.youtube.com/watch?v=-2XItBbxSto',
	'https://www.youtube.com/watch?v=g9as2CQPy7M',
	'https://www.youtube.com/watch?v=5h0zV_8nNko',
	'https://www.youtube.com/watch?v=zBMxVfcbli4',
	'https://www.youtube.com/watch?v=T9t51XoCR3g',
	'https://www.youtube.com/watch?v=HMJJ35BZK_g',
	'https://www.youtube.com/watch?v=O18mcC_wqwc',
	'https://www.youtube.com/watch?v=bNSqjHLb6MU',
	'https://www.youtube.com/watch?v=Rhvh13v1VzQ',
	'https://www.youtube.com/watch?v=LtUH-Oj2qUo',
	'https://www.youtube.com/watch?v=5ETHy1DkhBk',
	'https://www.youtube.com/watch?v=L0AGrHOtbj4',
	'https://www.youtube.com/watch?v=eL7gDSLDCgU',
	'https://www.youtube.com/watch?v=9mDh42chIhQ',
	'https://www.youtube.com/watch?v=n3r1MUd_D0M',
	'https://www.youtube.com/watch?v=_tUNvawSSRM',
	'https://www.youtube.com/watch?v=H3e4eXuC51s',
	'https://www.youtube.com/watch?v=SjJKGcsbESo',
	'https://www.youtube.com/watch?v=4dZ-GbdtS0U',
	'https://www.youtube.com/watch?v=y_vcOpBdc1c',
	'https://www.youtube.com/watch?v=fsXzduunBOs',
	'https://www.youtube.com/watch?v=y9yajPL82wQ',
	'https://www.youtube.com/watch?v=nz35ofz6Zxo',
	'https://www.youtube.com/watch?v=Jrrf-Uy2n4I',
	'https://www.youtube.com/watch?v=Rds8pdRCI-U',
	'https://www.youtube.com/watch?v=sEzVn2A1lOA',
	'https://www.youtube.com/watch?v=FRU_HZWSSlM',
	'https://www.youtube.com/watch?v=2FjixP1nMVg',
	'https://www.youtube.com/watch?v=bHGhoXzG4EU',
	'https://www.youtube.com/watch?v=dUzvNkQ9qsI',
	'https://www.youtube.com/watch?v=8XR5ZKAZzwE',
	'https://www.youtube.com/watch?v=P60KKsgyWwk',
	'https://www.youtube.com/watch?v=gHTBMTs2FZY',
	'https://www.youtube.com/watch?v=4gwAw3yHBZA',
	'https://www.youtube.com/watch?v=dFOCdTokhzw',
	'https://www.youtube.com/watch?v=oa25s_6Sfn0',
]
times = [876,832,474,323,548,399,616,437,513,337,470,449,448,159,535,766,660,602,598,901,784,422,850,772,901,517,765,892,562,901,225,335,518,707,861,834,711,712,472,237,563,675,863,865,897,167,222,890,1217,841,901,616,265,901,641,1390,794,791,901,895,901,834,901,901,679,901,804,901,901,891,901,901,901,170,1069,898,1058,1080,1723,1118,765,2141,2617,896,2654,1959]
comments = [
	"Frankly, my dear, I don’t give a damn",
	"I’m going to make him an offer he can’t refuse",
	"You don’t understand! I coulda had class. I coulda been a contender. I could’ve been somebody, instead of a bum, which is what I am",
	"Toto, I’ve got a feeling we’re not in Kansas anymore[1]",
	"Here’s looking at you, kid",
	"Go ahead, make my day!",
	"All right, Mr. DeMille, I’m ready for my close-up",
	"May the Force be with you!",
	"Fasten your seatbelts. It’s going to be a bumpy night",
	"You talkin' to me?",
	"What we’ve got here is (a) failure to communicate",
	"I love the smell of napalm in the morning!",
	"Love means never having to say you’re sorry",
	"The stuff that dreams are made of",
	"E.T. phone home",
	"They call me Mister Tibbs!",
	"Made it, Ma! Top of the world!",
	"I’m as mad as hell, and I’m not going to take this anymore!",
	"Louis, I think this is the beginning of a beautiful friendship",
	"A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti",
	"Bond. James Bond",
	"There’s no place like home",
	"I am big! It’s the pictures that got small",
	"Show me the money!",
	"Why don’t you come up sometime and see me?",
	"I’m walking here! I’m walking here!",
	"Play it, Sam. Play 'As Time Goes By.'",
	"You can’t handle the truth!",
	"I want to be alone",
	"After all, tomorrow is another day!",
	"Round up the usual suspects",
	"I’ll have what she’s having",
	"You know how to whistle, don’t you, Steve? You just put your lips together and blow",
	"You’re gonna need a bigger boat",
	"Badges? We ain’t got no badges! We don’t need no badges! I don’t have to show you any stinking badges!",
	"Today, I consider myself the luckiest man on the face of the earth",
	"If you build it, they will come",
	"Mama always said life was like a box of chocolates. You never know what you’re gonna get",
	"We’ll always have Paris",
	"I see dead people",
	"Stella! Hey, Stella!",
	"Oh, Jerry, don’t let’s ask for the moon. We have the stars",
	"Shane. Shane. Come back!",
	"Well, nobody’s perfect",
	"It’s alive! It’s alive!",
	"Houston, we have a problem",
	"You’ve got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?",
	"You had me at 'hello'",
	"One morning I shot an elephant in my pajamas. How he got in my pajamas, I don’t know",
	"There’s no crying in baseball!",
	"La-dee-da, la-dee-da",
	"A boy’s best friend is his mother",
	"Greed, for lack of a better word, is good",
	"Keep your friends close, but your enemies closer",
	"As God is my witness, I’ll never be hungry again",
	"Well, here’s another nice mess you’ve gotten me into!",
	"Say 'hello' to my little friend!",
	"Mrs. Robinson, you’re trying to seduce me. Aren’t you?",
	"Gentlemen, you can’t fight in here! This is the War Room!",
	"Elementary, my dear Watson",
	"Get your stinking paws off me, you damned dirty ape",
	"Of all the gin joints in all the towns in all the world, she walks into mine",
	"Here’s Johnny!",
	"Wait a minute, wait a minute. You ain't heard nothin' yet!",
	"No wire hangers, ever!",
	"Mother of mercy, is this the end of Rico?",
	"Forget it, Jake, it's Chinatown",
	"I have always depended on the kindness of strangers",
	"Hasta la vista, baby",
	"Soylent Green is people!",
	"Open the pod bay doors, HAL",
	"Hello, gorgeous",
	"Listen to them. Children of the night. What music they make",
	"Oh, no, it wasn’t the airplanes. It was Beauty killed the Beast",
	"Sawyer, you're going out a youngster, but you've got to come back a star!",
	"Listen to me, mister. You're my knight in shining armor. Don't you forget it. You're going to get back on that horse, and I'm going to be right behind you, holding on tight, and away we're gonna go, go, go!",
	"Tell 'em to go out there with all they got and win just one for the Gipper.",
	"A martini. Shaken, not stirred",
	"Cinderella story. Outta nowhere. A former greenskeeper, now, about to become the Masters champion. It looks like a mirac...It's in the hole! It's in the hole! It's in the hole!",
	"Life is a banquet, and most poor suckers are starving to death!",
	"I feel the need — the need for speed!",
	"Carpe diem. Seize the day, boys. Make your lives extraordinary",
	"Snap out of it!",
	"My mother thanks you. My father thanks you. My sister thanks you. And I thank you.",
	"Nobody puts Baby in a corner.",
	"I’ll get you, my pretty, and your little dog too!",
	"I’m the king of the world!"
]